### ISSUE TITLE
An Exception occurs in ESAC when adding some connections

### ISSUE THREAD

**Issue by CptMauli** [eclipse/neoscada#3]
An Exception occurs in ESAC (NeoSCADA Admin Client) when adding some connections.

I could observe it for connections containing an ! within the password.

**Comment by ctron** [comment]
Connections are again encoded as URIs. I guess that there can be an issue when things are not properly encoded.

Maybe using some kind of URI library would be a better approach. 😉

**Comment by CptMauli** [comment]
It apparently happens when the port is omitted!
