### ISSUE TITLE
Drag & Drop in ESAC fails for items which have a "+" (plus) in its id

### ISSUE THREAD

**Issue by CptMauli** [eclipse/neoscada#4]
Drag & Drop in ESAC (NeoSCADA Admin Client) fails for items which have a "+" (plus) in its id

**Comment by ctron** [comment]
IIRC the items are encoded as URI when they are passed on to the DnD handler. This could be an issue.

**Comment by CptMauli** [comment]
I know, but then there seems to be one place where it is not en- or decoded. I guess it will be an easy fix.
